export {default as Title} from "./Title"
export {default as AlgorithmDropDown} from "./AlgorithmDropDown"
export {default as AlgorithmComparisons} from "./AlgorithmComparisons"
export {default as AmountOfBarsSlider} from "./AmountOfBarsSlider"
export {default as CurrentAlgorithm} from "./CurrentAlgorithm"
export {default as StartButton} from "./StartButton"
export {default as VisualisationSpeedSlider} from "./VisualisationSpeedSlider"